name: "Report an Issue"
description: "Create a report for an issue or a bug"
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for considering about contributing to IINA and making it even better! To help us focus on unique issues, please first check out the existing issues, including closed ones. If you see someone else has already opened an issue about the same stuff, you should reply to their existing issue instead of opening a new one.

- type: input
  attributes:
    label: IINA Version
  validations:
    required: true

- type: dropdown
  attributes:
    label: Release Channel
    options: 
      - Release
      - Beta
      - Nightly
      - Other
      - Not Sure
    description: "If \"Other\" is selected, please specify in the IINA version text field."
  validations:
    required: true

- type: input
  attributes:
    label: macOS Version
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce
    value: |-
      - First step...
      - Second step...
      - ...
    render: text
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    render: text
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual Behavior
    render: text
  validations:
    reuiqred: true

- type: textarea
  attributes:
    label: Crash Report
    render: text
    description: If you're reporting a crash, please drag and drop the trace log file below. You can find these in ~/Library/Logs/DiagnosticReports/; the filename should prefixed with IINA and include the crash time.
    placeholder: Drag and drop the log file here; do not paste the content directly.

- type: textarea
  attributes:
    label: Logs
    render: text
    description: Please provide the log if applicable when after reproducing the issue. If you haven't done so already, you can enable logging in Preferences > Advanced.
    placeholder: Drag and drop the log file here; do not paste the content directly.

- type: textarea
  attributes:
    label: Sample Files
    render: text
    description: If the issue or bug is related to a specific file/file type (including subtitles), please provide sample files for us to reproduce. Please zip into one file if there are multiple files. For small files, just drag and drop into the text field below. For larger files, please consider uploading to file hosting services which can be freely accessible by us (e.g. Google Drive, iCloud Drive, etc).
    placeholder: Drag and drop the sample files, or paste the link of the files.

- type: input
  attributes:
    label: How often can you reproduce the issue
  validations:
    required: true

- type: checkboxes
  attributes:
    label: |
      Required actions
    options:
      - label: I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.
        required: true
- type: checkboxes
  attributes:
    label: |
      Optional actions
    options:
      - label: I tested with the Nightly build and confirmed the issue is not fixed.
      - label: I tested with the latest version of mpv and confirmed mpv doesn't have this issue.
      
